/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The JSON body that the invoked endpoint returned.
 */
export class BatchResponseBody extends SpeakeasyBase {}

/**
 * A map of HTTP headers specific to this result. This is primarily used for returning a `Location` header to accompany a `201 Created` result.  The parent HTTP response will contain all common headers.
 */
export class BatchResponseHeaders extends SpeakeasyBase {}

/**
 * A response object returned from a batch request.
 */
export class BatchResponse extends SpeakeasyBase {
    /**
     * The JSON body that the invoked endpoint returned.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "body" })
    @Type(() => BatchResponseBody)
    body?: BatchResponseBody;

    /**
     * A map of HTTP headers specific to this result. This is primarily used for returning a `Location` header to accompany a `201 Created` result.  The parent HTTP response will contain all common headers.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "headers" })
    @Type(() => BatchResponseHeaders)
    headers?: BatchResponseHeaders;

    /**
     * The HTTP status code that the invoked endpoint returned.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status_code" })
    statusCode?: number;
}
