/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EnumOption } from "./enumoption";
import { UserCompact } from "./usercompact";
import { Expose, Type } from "class-transformer";

/**
 * *Conditional*. A unique identifier to associate this field with the template source of truth.
 */
export enum CustomFieldResponseAsanaCreatedField {
    AVRequirements = "a_v_requirements",
    AccountName = "account_name",
    Actionable = "actionable",
    AlignShippingLink = "align_shipping_link",
    AlignStatus = "align_status",
    AllottedTime = "allotted_time",
    Appointment = "appointment",
    ApprovalStage = "approval_stage",
    Approved = "approved",
    ArticleSeries = "article_series",
    BoardCommittee = "board_committee",
    Browser = "browser",
    CampaignAudience = "campaign_audience",
    CampaignProjectStatus = "campaign_project_status",
    CampaignRegions = "campaign_regions",
    ChannelPrimary = "channel_primary",
    ClientTopicType = "client_topic_type",
    CompleteBy = "complete_by",
    Contact = "contact",
    ContactEmailAddress = "contact_email_address",
    ContentChannels = "content_channels",
    ContentChannelsNeeded = "content_channels_needed",
    ContentStage = "content_stage",
    ContentType = "content_type",
    Contract = "contract",
    ContractStatus = "contract_status",
    Cost = "cost",
    CreationStage = "creation_stage",
    CreativeChannel = "creative_channel",
    CreativeNeeded = "creative_needed",
    CreativeNeeds = "creative_needs",
    DataSensitivity = "data_sensitivity",
    DealSize = "deal_size",
    DeliveryAppt = "delivery_appt",
    DeliveryApptDate = "delivery_appt_date",
    Department = "department",
    DepartmentResponsible = "department_responsible",
    DesignRequestNeeded = "design_request_needed",
    DesignRequestType = "design_request_type",
    DiscussionCategory = "discussion_category",
    DoThisTask = "do_this_task",
    EditorialContentStatus = "editorial_content_status",
    EditorialContentTag = "editorial_content_tag",
    EditorialContentType = "editorial_content_type",
    Effort = "effort",
    EffortLevel = "effort_level",
    EstCompletionDate = "est_completion_date",
    EstimatedTime = "estimated_time",
    EstimatedValue = "estimated_value",
    ExpectedCost = "expected_cost",
    ExternalStepsNeeded = "external_steps_needed",
    FavoriteIdea = "favorite_idea",
    FeedbackType = "feedback_type",
    Financial = "financial",
    FundingAmount = "funding_amount",
    GrantApplicationProcess = "grant_application_process",
    HiringCandidateStatus = "hiring_candidate_status",
    IdeaStatus = "idea_status",
    IdsLink = "ids_link",
    IdsPatientLink = "ids_patient_link",
    ImplementationStage = "implementation_stage",
    Insurance = "insurance",
    InterviewArea = "interview_area",
    InterviewQuestionScore = "interview_question_score",
    IteroScanLink = "itero_scan_link",
    JobSAppliedTo = "job_s_applied_to",
    Lab = "lab",
    LaunchStatus = "launch_status",
    LeadStatus = "lead_status",
    LocalizationLanguage = "localization_language",
    LocalizationMarketTeam = "localization_market_team",
    LocalizationStatus = "localization_status",
    MeetingMinutes = "meeting_minutes",
    MeetingNeeded = "meeting_needed",
    Minutes = "minutes",
    Mrr = "mrr",
    MustLocalize = "must_localize",
    NameOfFoundation = "name_of_foundation",
    NeedToFollowUp = "need_to_follow_up",
    NextAppointment = "next_appointment",
    NextStepsSales = "next_steps_sales",
    NumPeople = "num_people",
    NumberOfUserReports = "number_of_user_reports",
    OfficeLocation = "office_location",
    OnboardingActivity = "onboarding_activity",
    Owner = "owner",
    ParticipantsNeeded = "participants_needed",
    PatientDateOfBirth = "patient_date_of_birth",
    PatientEmail = "patient_email",
    PatientPhone = "patient_phone",
    PatientStatus = "patient_status",
    PhoneNumber = "phone_number",
    PlanningCategory = "planning_category",
    PointOfContact = "point_of_contact",
    Position = "position",
    PostFormat = "post_format",
    Prescription = "prescription",
    Priority = "priority",
    PriorityLevel = "priority_level",
    Product = "product",
    ProductStage = "product_stage",
    Progress = "progress",
    ProjectSize = "project_size",
    ProjectStatus = "project_status",
    ProposedBudget = "proposed_budget",
    PublishStatus = "publish_status",
    ReasonForScan = "reason_for_scan",
    Referral = "referral",
    RequestType = "request_type",
    ResearchStatus = "research_status",
    ResponsibleDepartment = "responsible_department",
    ResponsibleTeam = "responsible_team",
    RiskAssessmentStatus = "risk_assessment_status",
    RoomName = "room_name",
    SalesCounterpart = "sales_counterpart",
    Sentiment = "sentiment",
    ShippingLink = "shipping_link",
    SocialChannels = "social_channels",
    Stage = "stage",
    Status = "status",
    StatusDesign = "status_design",
    StatusOfInitiative = "status_of_initiative",
    SystemSetup = "system_setup",
    TaskProgress = "task_progress",
    Team = "team",
    TeamMarketing = "team_marketing",
    TeamResponsible = "team_responsible",
    TimeItTakesToCompleteTasks = "time_it_takes_to_complete_tasks",
    Timeframe = "timeframe",
    TreatmentType = "treatment_type",
    TypeWorkRequestsIt = "type_work_requests_it",
    UseAgency = "use_agency",
    UserName = "user_name",
    VendorCategory = "vendor_category",
    VendorType = "vendor_type",
    WordCount = "word_count",
}

/**
 * Only relevant for custom fields with `custom` format. This depicts where to place the custom label. This will be null if the `format` is not `custom`.
 */
export enum CustomFieldResponseCustomLabelPosition {
    Prefix = "prefix",
    Suffix = "suffix",
}

/**
 * *Conditional*. Only relevant for custom fields of type `date`. This object reflects the chosen date (and optionally, time) value of a `date` custom field. If no date is selected, the value of `date_value` will be `null`.
 */
export class CustomFieldResponseDateValue extends SpeakeasyBase {
    /**
     * A string representing the date in YYYY-MM-DD format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "date" })
    date?: string;

    /**
     * A string representing the date in ISO 8601 format. If no time value is selected, the value of `date-time` will be `null`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "date_time" })
    dateTime?: string;
}

/**
 * Enum options are the possible values which an enum custom field can adopt. An enum custom field must contain at least 1 enum option but no more than 500.
 *
 * @remarks
 *
 * You can add enum options to a custom field by using the `POST /custom_fields/custom_field_gid/enum_options` endpoint.
 *
 * **It is not possible to remove or delete an enum option**. Instead, enum options can be disabled by updating the `enabled` field to false with the `PUT /enum_options/enum_option_gid` endpoint. Other attributes can be updated similarly.
 *
 * On creation of an enum option, `enabled` is always set to `true`, meaning the enum option is a selectable value for the custom field. Setting `enabled=false` is equivalent to “trashing” the enum option in the Asana web app within the “Edit Fields” dialog. The enum option will no longer be selectable but, if the enum option value was previously set within a task, the task will retain the value.
 *
 * Enum options are an ordered list and by default new enum options are inserted at the end. Ordering in relation to existing enum options can be specified on creation by using `insert_before` or `insert_after` to reference an existing enum option. Only one of `insert_before` and `insert_after` can be provided when creating a new enum option.
 *
 * An enum options list can be reordered with the `POST /custom_fields/custom_field_gid/enum_options/insert` endpoint.
 */
export class CustomFieldResponseEnumValue extends SpeakeasyBase {
    /**
     * The color of the enum option. Defaults to ‘none’.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "color" })
    color?: string;

    /**
     * Whether or not the enum option is a selectable value for the custom field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "enabled" })
    enabled?: boolean;

    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * The name of the enum option.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;
}

/**
 * The format of this custom field.
 */
export enum CustomFieldResponseFormat {
    Currency = "currency",
    Identifier = "identifier",
    Percentage = "percentage",
    Custom = "custom",
    None = "none",
}

/**
 * The type of the custom field. Must be one of the given values.
 *
 * @remarks
 *
 */
export enum CustomFieldResponseResourceSubtype {
    Text = "text",
    Enum = "enum",
    MultiEnum = "multi_enum",
    Number = "number",
    Date = "date",
    People = "people",
}

/**
 * *Deprecated: new integrations should prefer the resource_subtype field.* The type of the custom field. Must be one of the given values.
 *
 * @remarks
 *
 */
export enum CustomFieldResponseType {
    Text = "text",
    Enum = "enum",
    MultiEnum = "multi_enum",
    Number = "number",
}

/**
 * Custom Fields store the metadata that is used in order to add user-specified information to tasks in Asana. Be sure to reference the [Custom Fields](/docs/asana-custom-fields) developer documentation for more information about how custom fields relate to various resources in Asana.
 *
 * @remarks
 *
 * Users in Asana can [lock custom fields](https://asana.com/guide/help/premium/custom-fields#gl-lock-fields), which will make them read-only when accessed by other users. Attempting to edit a locked custom field will return HTTP error code `403 Forbidden`.
 */
export class CustomFieldResponse extends SpeakeasyBase {
    /**
     * *Conditional*. A unique identifier to associate this field with the template source of truth.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "asana_created_field" })
    asanaCreatedField?: CustomFieldResponseAsanaCreatedField;

    @SpeakeasyMetadata()
    @Expose({ name: "created_by" })
    @Type(() => UserCompact)
    createdBy?: UserCompact;

    /**
     * ISO 4217 currency code to format this custom field. This will be null if the `format` is not `currency`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency_code" })
    currencyCode?: string;

    /**
     * This is the string that appears next to the custom field value. This will be null if the `format` is not `custom`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "custom_label" })
    customLabel?: string;

    /**
     * Only relevant for custom fields with `custom` format. This depicts where to place the custom label. This will be null if the `format` is not `custom`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "custom_label_position" })
    customLabelPosition?: CustomFieldResponseCustomLabelPosition;

    /**
     * *Conditional*. Only relevant for custom fields of type `date`. This object reflects the chosen date (and optionally, time) value of a `date` custom field. If no date is selected, the value of `date_value` will be `null`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "date_value" })
    @Type(() => CustomFieldResponseDateValue)
    dateValue?: CustomFieldResponseDateValue;

    /**
     * [Opt In](/docs/input-output-options). The description of the custom field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * A string representation for the value of the custom field. Integrations that don't require the underlying type should use this field to read values. Using this field will future-proof an app against new custom field types.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "display_value" })
    displayValue?: string;

    /**
     * *Conditional*. Determines if the custom field is enabled or not.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "enabled" })
    enabled?: boolean;

    /**
     * *Conditional*. Only relevant for custom fields of type `enum`. This array specifies the possible values which an `enum` custom field can adopt. To modify the enum options, refer to [working with enum options](/docs/create-an-enum-option).
     */
    @SpeakeasyMetadata({ elemType: EnumOption })
    @Expose({ name: "enum_options" })
    @Type(() => EnumOption)
    enumOptions?: EnumOption[];

    @SpeakeasyMetadata()
    @Expose({ name: "enum_value" })
    @Type(() => CustomFieldResponseEnumValue)
    enumValue?: CustomFieldResponseEnumValue;

    /**
     * The format of this custom field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "format" })
    format?: CustomFieldResponseFormat;

    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * *Conditional*. This flag describes whether a follower of a task with this field should receive inbox notifications from changes to this field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "has_notifications_enabled" })
    hasNotificationsEnabled?: boolean;

    /**
     * This flag describes whether this custom field is available to every container in the workspace. Before project-specific custom fields, this field was always true.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "is_global_to_workspace" })
    isGlobalToWorkspace?: boolean;

    /**
     * *Conditional*. Only relevant for custom fields of type `multi_enum`. This object is the chosen values of a `multi_enum` custom field.
     */
    @SpeakeasyMetadata({ elemType: EnumOption })
    @Expose({ name: "multi_enum_values" })
    @Type(() => EnumOption)
    multiEnumValues?: EnumOption[];

    /**
     * The name of the custom field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * *Conditional*. This number is the value of a `number` custom field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "number_value" })
    numberValue?: number;

    /**
     * *Conditional*. Only relevant for custom fields of type `people`. This array of [compact user](/docs/user-compact) objects reflects the values of a `people` custom field.
     */
    @SpeakeasyMetadata({ elemType: UserCompact })
    @Expose({ name: "people_value" })
    @Type(() => UserCompact)
    peopleValue?: UserCompact[];

    /**
     * Only relevant for custom fields of type ‘Number’. This field dictates the number of places after the decimal to round to, i.e. 0 is integer values, 1 rounds to the nearest tenth, and so on. Must be between 0 and 6, inclusive.
     *
     * @remarks
     * For percentage format, this may be unintuitive, as a value of 0.25 has a precision of 0, while a value of 0.251 has a precision of 1. This is due to 0.25 being displayed as 25%.
     * The identifier format will always have a precision of 0.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "precision" })
    precision?: number;

    /**
     * The type of the custom field. Must be one of the given values.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_subtype" })
    resourceSubtype?: CustomFieldResponseResourceSubtype;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;

    /**
     * *Conditional*. This string is the value of a `text` custom field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "text_value" })
    textValue?: string;

    /**
     * *Deprecated: new integrations should prefer the resource_subtype field.* The type of the custom field. Must be one of the given values.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: CustomFieldResponseType;
}
