/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase } from "../../../internal/utils";

/**
 * An empty object. Some endpoints do not return an object on success. The success is conveyed through a 2-- status code and returning an empty object.
 */
export class EmptyResponse extends SpeakeasyBase {}
