/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Like } from "./like";
import { UserCompact } from "./usercompact";
import { Expose, Type } from "class-transformer";

/**
 * The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
 *
 * @remarks
 * The `resource_subtype`s for `status` objects represent the type of their parent.
 */
export enum GoalResponseCurrentStatusUpdateResourceSubtype {
    ProjectStatusUpdate = "project_status_update",
    PortfolioStatusUpdate = "portfolio_status_update",
    GoalStatusUpdate = "goal_status_update",
}

/**
 * A *status update* is an update on the progress of a particular project, portfolio, or goal, and is sent out to all of its parent's followers when created. These updates include both text describing the update and a `status_type` intended to represent the overall state of the project.
 */
export class GoalResponseCurrentStatusUpdate extends SpeakeasyBase {
    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
     *
     * @remarks
     * The `resource_subtype`s for `status` objects represent the type of their parent.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_subtype" })
    resourceSubtype?: GoalResponseCurrentStatusUpdateResourceSubtype;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;

    /**
     * The title of the status update.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title?: string;
}

/**
 * This field defines how the progress value of a goal metric is being calculated. A goal's progress can be provided manually by the user, calculated automatically from contributing subgoals or projects, or managed by an integration with an external data source, such as Salesforce.
 */
export enum GoalResponseMetricProgressSource {
    Manual = "manual",
    SubgoalProgress = "subgoal_progress",
    ProjectTaskCompletion = "project_task_completion",
    ProjectMilestoneCompletion = "project_milestone_completion",
    External = "external",
}

/**
 * The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
 */
export enum GoalResponseMetricResourceSubtype {
    Number = "number",
}

/**
 * A supported unit of measure for the goal metric, or none.
 */
export enum GoalResponseMetricUnit {
    None = "none",
    Currency = "currency",
    Percentage = "percentage",
}

/**
 * A generic Asana Resource, containing a globally unique identifier.
 */
export class GoalResponseMetric extends SpeakeasyBase {
    /**
     * *Conditional*. Only relevant for `progress_source` of type `external`. This boolean indicates whether the requester has the ability to update the current value of this metric. This returns `true` if the external metric was created by the requester, `false` otherwise.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "can_manage" })
    canManage?: boolean;

    /**
     * ISO 4217 currency code to format this custom field. This will be null if the `unit` is not `currency`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency_code" })
    currencyCode?: string;

    /**
     * This string is the current value of a goal metric of type string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "current_display_value" })
    currentDisplayValue?: string;

    /**
     * This number is the current value of a goal metric of type number.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "current_number_value" })
    currentNumberValue?: number;

    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * This number is the start value of a goal metric of type number.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "initial_number_value" })
    initialNumberValue?: number;

    /**
     * *Conditional*. Only relevant for goal metrics of type ‘Number’. This field dictates the number of places after the decimal to round to, i.e. 0 is integer values, 1 rounds to the nearest tenth, and so on. Must be between 0 and 6, inclusive.
     *
     * @remarks
     * For percentage format, this may be unintuitive, as a value of 0.25 has a precision of 0, while a value of 0.251 has a precision of 1. This is due to 0.25 being displayed as 25%.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "precision" })
    precision?: number;

    /**
     * This field defines how the progress value of a goal metric is being calculated. A goal's progress can be provided manually by the user, calculated automatically from contributing subgoals or projects, or managed by an integration with an external data source, such as Salesforce.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "progress_source" })
    progressSource?: GoalResponseMetricProgressSource;

    /**
     * The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_subtype" })
    resourceSubtype?: GoalResponseMetricResourceSubtype;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;

    /**
     * This number is the end value of a goal metric of type number. This number cannot equal `initial_number_value`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "target_number_value" })
    targetNumberValue?: number;

    /**
     * A supported unit of measure for the goal metric, or none.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit" })
    unit?: GoalResponseMetricUnit;
}

/**
 * A *user* object represents an account in Asana that can be given access to various workspaces, projects, and tasks.
 */
export class GoalResponseOwner extends SpeakeasyBase {
    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * *Read-only except when same user as requester*. The user’s name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;
}

/**
 * A *team* is used to group related projects and people together within an organization. Each project in an organization is associated with a team.
 */
export class GoalResponseTeam extends SpeakeasyBase {
    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * The name of the team.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;
}

/**
 * The cadence and index of the time period. The value is one of: `FY`, `H1`, `H2`, `Q1`, `Q2`, `Q3`, or `Q4`.
 */
export enum GoalResponseTimePeriodPeriod {
    Fy = "FY",
    H1 = "H1",
    H2 = "H2",
    Q1 = "Q1",
    Q2 = "Q2",
    Q3 = "Q3",
    Q4 = "Q4",
}

/**
 * A generic Asana Resource, containing a globally unique identifier.
 */
export class GoalResponseTimePeriod extends SpeakeasyBase {
    /**
     * A string representing the cadence code and the fiscal year.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "display_name" })
    displayName?: string;

    /**
     * The localized end date of the time period in `YYYY-MM-DD` format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "end_on" })
    endOn?: string;

    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * The cadence and index of the time period. The value is one of: `FY`, `H1`, `H2`, `Q1`, `Q2`, `Q3`, or `Q4`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "period" })
    period?: GoalResponseTimePeriodPeriod;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;

    /**
     * The localized start date of the time period in `YYYY-MM-DD` format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "start_on" })
    startOn?: string;
}

/**
 * A *workspace* is the highest-level organizational unit in Asana. All projects and tasks have an associated workspace.
 */
export class GoalResponseWorkspace extends SpeakeasyBase {
    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * The name of the workspace.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;
}

/**
 * A generic Asana Resource, containing a globally unique identifier.
 */
export class GoalResponse extends SpeakeasyBase {
    /**
     * The latest `status_update` posted to this goal.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "current_status_update" })
    @Type(() => GoalResponseCurrentStatusUpdate)
    currentStatusUpdate?: GoalResponseCurrentStatusUpdate;

    /**
     * The localized day on which this goal is due. This takes a date with format `YYYY-MM-DD`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "due_on" })
    dueOn?: string;

    /**
     * Array of users who are members of this goal.
     */
    @SpeakeasyMetadata({ elemType: UserCompact })
    @Expose({ name: "followers" })
    @Type(() => UserCompact)
    followers?: UserCompact[];

    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * The notes of the goal with formatting as HTML.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "html_notes" })
    htmlNotes?: string;

    /**
     * *Conditional*. This property is only present when the `workspace` provided is an organization. Whether the goal belongs to the `workspace` (and is listed as part of the workspace’s goals) or not. If it isn’t a workspace-level goal, it is a team-level goal, and is associated with the goal’s team.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "is_workspace_level" })
    isWorkspaceLevel?: boolean;

    /**
     * True if the goal is liked by the authorized user, false if not.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "liked" })
    liked?: boolean;

    /**
     * Array of likes for users who have liked this goal.
     */
    @SpeakeasyMetadata({ elemType: Like })
    @Expose({ name: "likes" })
    @Type(() => Like)
    likes?: Like[];

    @SpeakeasyMetadata()
    @Expose({ name: "metric" })
    @Type(() => GoalResponseMetric)
    metric?: GoalResponseMetric;

    /**
     * The name of the goal.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Free-form textual information associated with the goal (i.e. its description).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "notes" })
    notes?: string;

    /**
     * The number of users who have liked this goal.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "num_likes" })
    numLikes?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "owner" })
    @Type(() => GoalResponseOwner)
    owner?: GoalResponseOwner;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;

    /**
     * The day on which work for this goal begins, or null if the goal has no start date. This takes a date with `YYYY-MM-DD` format, and cannot be set unless there is an accompanying due date.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "start_on" })
    startOn?: string;

    /**
     * The current status of this goal. When the goal is open, its status can be `green`, `yellow`, and `red` to reflect "On Track", "At Risk", and "Off Track", respectively. When the goal is closed, the value can be `missed`, `achieved`, `partial`, or `dropped`.
     *
     * @remarks
     * *Note* you can only write to this property if `metric` is set.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;

    /**
     * *Conditional*. This property is only present when the `workspace` provided is an organization.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "team" })
    @Type(() => GoalResponseTeam)
    team?: GoalResponseTeam;

    @SpeakeasyMetadata()
    @Expose({ name: "time_period" })
    @Type(() => GoalResponseTimePeriod)
    timePeriod?: GoalResponseTimePeriod;

    @SpeakeasyMetadata()
    @Expose({ name: "workspace" })
    @Type(() => GoalResponseWorkspace)
    workspace?: GoalResponseWorkspace;
}
