/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A generic Asana Resource, containing a globally unique identifier.
 */
export class GoalMetricCurrentValueRequestInput extends SpeakeasyBase {
    /**
     * *Conditional*. This number is the current value of a goal metric of type number.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "current_number_value" })
    currentNumberValue?: number;
}
