/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A set of dependent tasks.
 */
export class ModifyDependentsRequest extends SpeakeasyBase {
    /**
     * An array of task gids that are dependents of the given task.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "dependents" })
    dependents?: string[];
}
