/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class PortfolioAddItemRequest extends SpeakeasyBase {
    /**
     * An id of an item in this portfolio. The new item will be added after the one specified here. `insert_before` and `insert_after` parameters cannot both be specified.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "insert_after" })
    insertAfter?: string;

    /**
     * An id of an item in this portfolio. The new item will be added before the one specified here. `insert_before` and `insert_after` parameters cannot both be specified.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "insert_before" })
    insertBefore?: string;

    /**
     * The item to add to the portfolio.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "item" })
    item: string;
}
