/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A *Project Brief* allows you to explain the what and why of the project to your team.
 */
export class ProjectBriefRequestInput extends SpeakeasyBase {
    /**
     * HTML formatted text for the project brief.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "html_text" })
    htmlText?: string;

    /**
     * The plain text of the project brief. When writing to a project brief, you can specify either `html_text` (preferred) or `text`, but not both.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "text" })
    text?: string;

    /**
     * The title of the project brief.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title?: string;
}
