/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RFCDate } from "../../types";
import { AsanaResource } from "./asanaresource";
import { CustomFieldResponse } from "./customfieldresponse";
import { Like } from "./like";
import { ProjectCompact } from "./projectcompact";
import { SectionCompact } from "./sectioncompact";
import { TagCompact } from "./tagcompact";
import { UserCompact } from "./usercompact";
import { Expose, Transform, Type } from "class-transformer";

/**
 * *Conditional* Reflects the approval status of this task. This field is kept in sync with `completed`, meaning `pending` translates to false while `approved`, `rejected`, and `changes_requested` translate to true. If you set completed to true, this field will be set to `approved`.
 */
export enum TaskResponseApprovalStatus {
    Pending = "pending",
    Approved = "approved",
    Rejected = "rejected",
    ChangesRequested = "changes_requested",
}

/**
 * A *user* object represents an account in Asana that can be given access to various workspaces, projects, and tasks.
 */
export class TaskResponseAssignee extends SpeakeasyBase {
    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * *Read-only except when same user as requester*. The user’s name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;
}

/**
 * A *section* is a subdivision of a project that groups tasks together. It can either be a header above a list of tasks in a list view or a column in a board view of a project.
 */
export class TaskResponseAssigneeSection extends SpeakeasyBase {
    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * The name of the section (i.e. the text displayed as the section header).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;
}

/**
 * *Deprecated* Scheduling status of this task for the user it is assigned to. This field can only be set if the assignee is non-null. Setting this field to "inbox" or "upcoming" inserts it at the top of the section, while the other options will insert at the bottom.
 */
export enum TaskResponseAssigneeStatus {
    Today = "today",
    Upcoming = "upcoming",
    Later = "later",
    New = "new",
    Inbox = "inbox",
}

/**
 * *OAuth Required*. *Conditional*. This field is returned only if external values are set or included by using [Opt In] (/docs/input-output-options).
 *
 * @remarks
 * The external field allows you to store app-specific metadata on tasks, including a gid that can be used to retrieve tasks and a data blob that can store app-specific character strings. Note that you will need to authenticate with Oauth to access or modify this data. Once an external gid is set, you can use the notation `external:custom_gid` to reference your object anywhere in the API where you may use the original object gid. See the page on Custom External Data for more details.
 */
export class TaskResponseExternal extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    data?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;
}

export class TaskResponseMemberships extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "project" })
    @Type(() => ProjectCompact)
    project?: ProjectCompact;

    @SpeakeasyMetadata()
    @Expose({ name: "section" })
    @Type(() => SectionCompact)
    section?: SectionCompact;
}

/**
 * The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
 *
 * @remarks
 * The resource_subtype `milestone` represent a single moment in time. This means tasks with this subtype cannot have a start_date.
 */
export enum TaskResponseParentResourceSubtype {
    DefaultTask = "default_task",
    Milestone = "milestone",
    Section = "section",
    Approval = "approval",
}

/**
 * The *task* is the basic object around which many operations in Asana are centered.
 */
export class TaskResponseParent extends SpeakeasyBase {
    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * The name of the task.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
     *
     * @remarks
     * The resource_subtype `milestone` represent a single moment in time. This means tasks with this subtype cannot have a start_date.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_subtype" })
    resourceSubtype?: TaskResponseParentResourceSubtype;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;
}

/**
 * The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
 *
 * @remarks
 * The resource_subtype `milestone` represent a single moment in time. This means tasks with this subtype cannot have a start_date.
 */
export enum TaskResponseResourceSubtype {
    DefaultTask = "default_task",
    Milestone = "milestone",
    Section = "section",
    Approval = "approval",
}

/**
 * A *workspace* is the highest-level organizational unit in Asana. All projects and tasks have an associated workspace.
 */
export class TaskResponseWorkspace extends SpeakeasyBase {
    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * The name of the workspace.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;
}

/**
 * The *task* is the basic object around which many operations in Asana are centered.
 */
export class TaskResponse extends SpeakeasyBase {
    /**
     * This value represents the sum of all the Time Tracking entries in the Actual Time field on a given Task. It is represented as a nullable long value.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "actual_time_minutes" })
    actualTimeMinutes?: number;

    /**
     * *Conditional* Reflects the approval status of this task. This field is kept in sync with `completed`, meaning `pending` translates to false while `approved`, `rejected`, and `changes_requested` translate to true. If you set completed to true, this field will be set to `approved`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "approval_status" })
    approvalStatus?: TaskResponseApprovalStatus;

    @SpeakeasyMetadata()
    @Expose({ name: "assignee" })
    @Type(() => TaskResponseAssignee)
    assignee?: TaskResponseAssignee;

    @SpeakeasyMetadata()
    @Expose({ name: "assignee_section" })
    @Type(() => TaskResponseAssigneeSection)
    assigneeSection?: TaskResponseAssigneeSection;

    /**
     * *Deprecated* Scheduling status of this task for the user it is assigned to. This field can only be set if the assignee is non-null. Setting this field to "inbox" or "upcoming" inserts it at the top of the section, while the other options will insert at the bottom.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "assignee_status" })
    assigneeStatus?: TaskResponseAssigneeStatus;

    /**
     * True if the task is currently marked complete, false if not.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "completed" })
    completed?: boolean;

    /**
     * The time at which this task was completed, or null if the task is incomplete.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "completed_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    completedAt?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "completed_by" })
    @Type(() => UserCompact)
    completedBy?: UserCompact;

    /**
     * The time at which this resource was created.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    createdAt?: Date;

    /**
     * Array of custom field values applied to the task. These represent the custom field values recorded on this project for a particular custom field. For example, these custom field values will contain an `enum_value` property for custom fields of type `enum`, a `text_value` property for custom fields of type `text`, and so on. Please note that the `gid` returned on each custom field value *is identical* to the `gid` of the custom field, which allows referencing the custom field metadata through the `/custom_fields/custom_field-gid` endpoint.
     */
    @SpeakeasyMetadata({ elemType: CustomFieldResponse })
    @Expose({ name: "custom_fields" })
    @Type(() => CustomFieldResponse)
    customFields?: CustomFieldResponse[];

    /**
     * [Opt In](/docs/input-output-options). Array of resources referencing tasks that this task depends on. The objects contain only the gid of the dependency.
     */
    @SpeakeasyMetadata({ elemType: AsanaResource })
    @Expose({ name: "dependencies" })
    @Type(() => AsanaResource)
    dependencies?: AsanaResource[];

    /**
     * [Opt In](/docs/input-output-options). Array of resources referencing tasks that depend on this task. The objects contain only the ID of the dependent.
     */
    @SpeakeasyMetadata({ elemType: AsanaResource })
    @Expose({ name: "dependents" })
    @Type(() => AsanaResource)
    dependents?: AsanaResource[];

    /**
     * The UTC date and time on which this task is due, or null if the task has no due time. This takes an ISO 8601 date string in UTC and should not be used together with `due_on`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "due_at" })
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    dueAt?: RFCDate;

    /**
     * The localized date on which this task is due, or null if the task has no due date. This takes a date with `YYYY-MM-DD` format and should not be used together with `due_at`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "due_on" })
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    dueOn?: RFCDate;

    /**
     * *OAuth Required*. *Conditional*. This field is returned only if external values are set or included by using [Opt In] (/docs/input-output-options).
     *
     * @remarks
     * The external field allows you to store app-specific metadata on tasks, including a gid that can be used to retrieve tasks and a data blob that can store app-specific character strings. Note that you will need to authenticate with Oauth to access or modify this data. Once an external gid is set, you can use the notation `external:custom_gid` to reference your object anywhere in the API where you may use the original object gid. See the page on Custom External Data for more details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "external" })
    @Type(() => TaskResponseExternal)
    external?: TaskResponseExternal;

    /**
     * Array of users following this task.
     */
    @SpeakeasyMetadata({ elemType: UserCompact })
    @Expose({ name: "followers" })
    @Type(() => UserCompact)
    followers?: UserCompact[];

    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * *Deprecated - please use liked instead* True if the task is hearted by the authorized user, false if not.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "hearted" })
    hearted?: boolean;

    /**
     * *Deprecated - please use likes instead* Array of likes for users who have hearted this task.
     */
    @SpeakeasyMetadata({ elemType: Like })
    @Expose({ name: "hearts" })
    @Type(() => Like)
    hearts?: Like[];

    /**
     * [Opt In](/docs/input-output-options). The notes of the text with formatting as HTML.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "html_notes" })
    htmlNotes?: string;

    /**
     * [Opt In](/docs/input-output-options). In some contexts tasks can be rendered as a visual separator; for instance, subtasks can appear similar to [sections](/docs/asana-sections) without being true `section` objects. If a `task` object is rendered this way in any context it will have the property `is_rendered_as_separator` set to `true`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "is_rendered_as_separator" })
    isRenderedAsSeparator?: boolean;

    /**
     * True if the task is liked by the authorized user, false if not.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "liked" })
    liked?: boolean;

    /**
     * Array of likes for users who have liked this task.
     */
    @SpeakeasyMetadata({ elemType: Like })
    @Expose({ name: "likes" })
    @Type(() => Like)
    likes?: Like[];

    /**
     * *Create-only*. Array of projects this task is associated with and the section it is in. At task creation time, this array can be used to add the task to specific sections. After task creation, these associations can be modified using the `addProject` and `removeProject` endpoints. Note that over time, more types of memberships may be added to this property.
     */
    @SpeakeasyMetadata({ elemType: TaskResponseMemberships })
    @Expose({ name: "memberships" })
    @Type(() => TaskResponseMemberships)
    memberships?: TaskResponseMemberships[];

    /**
     * The time at which this task was last modified.
     *
     * @remarks
     *
     * *Note: This does not currently reflect any changes in
     * associations such as projects or comments that may have been
     * added or removed from the task.*
     */
    @SpeakeasyMetadata()
    @Expose({ name: "modified_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    modifiedAt?: Date;

    /**
     * The name of the task.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Free-form textual information associated with the task (i.e. its description).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "notes" })
    notes?: string;

    /**
     * *Deprecated - please use likes instead* The number of users who have hearted this task.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "num_hearts" })
    numHearts?: number;

    /**
     * The number of users who have liked this task.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "num_likes" })
    numLikes?: number;

    /**
     * [Opt In](/docs/input-output-options). The number of subtasks on this task.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "num_subtasks" })
    numSubtasks?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "parent" })
    @Type(() => TaskResponseParent)
    parent?: TaskResponseParent;

    /**
     * A url that points directly to the object within Asana.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "permalink_url" })
    permalinkUrl?: string;

    /**
     * *Create-only.* Array of projects this task is associated with. At task creation time, this array can be used to add the task to many projects at once. After task creation, these associations can be modified using the addProject and removeProject endpoints.
     */
    @SpeakeasyMetadata({ elemType: ProjectCompact })
    @Expose({ name: "projects" })
    @Type(() => ProjectCompact)
    projects?: ProjectCompact[];

    /**
     * The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.
     *
     * @remarks
     * The resource_subtype `milestone` represent a single moment in time. This means tasks with this subtype cannot have a start_date.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_subtype" })
    resourceSubtype?: TaskResponseResourceSubtype;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;

    /**
     * Date and time on which work begins for the task, or null if the task has no start time. This takes an ISO 8601 date string in UTC and should not be used together with `start_on`.
     *
     * @remarks
     * *Note: `due_at` must be present in the request when setting or unsetting the `start_at` parameter.*
     */
    @SpeakeasyMetadata()
    @Expose({ name: "start_at" })
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    startAt?: RFCDate;

    /**
     * The day on which work begins for the task , or null if the task has no start date. This takes a date with `YYYY-MM-DD` format and should not be used together with `start_at`.
     *
     * @remarks
     * *Note: `due_on` or `due_at` must be present in the request when setting or unsetting the `start_on` parameter.*
     */
    @SpeakeasyMetadata()
    @Expose({ name: "start_on" })
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    startOn?: RFCDate;

    /**
     * Array of tags associated with this task. In order to change tags on an existing task use `addTag` and `removeTag`.
     */
    @SpeakeasyMetadata({ elemType: TagCompact })
    @Expose({ name: "tags" })
    @Type(() => TagCompact)
    tags?: TagCompact[];

    @SpeakeasyMetadata()
    @Expose({ name: "workspace" })
    @Type(() => TaskResponseWorkspace)
    workspace?: TaskResponseWorkspace;
}
