/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * A *workspace* is the highest-level organizational unit in Asana. All projects and tasks have an associated workspace.
 */
export class TeamResponseOrganization extends SpeakeasyBase {
    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * The name of the workspace.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;
}

/**
 * The visibility of the team to users in the same organization
 *
 * @remarks
 *
 */
export enum TeamResponseVisibility {
    Secret = "secret",
    RequestToJoin = "request_to_join",
    Public = "public",
}

/**
 * A *team* is used to group related projects and people together within an organization. Each project in an organization is associated with a team.
 */
export class TeamResponse extends SpeakeasyBase {
    /**
     * [Opt In](/docs/input-output-options). The description of the team.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * [Opt In](/docs/input-output-options). The description of the team with formatting as HTML.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "html_description" })
    htmlDescription?: string;

    /**
     * The name of the team.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "organization" })
    @Type(() => TeamResponseOrganization)
    organization?: TeamResponseOrganization;

    /**
     * A url that points directly to the object within Asana.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "permalink_url" })
    permalinkUrl?: string;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;

    /**
     * The visibility of the team to users in the same organization
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "visibility" })
    visibility?: TeamResponseVisibility;
}
