/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The cadence and index of the time period. The value is one of: `FY`, `H1`, `H2`, `Q1`, `Q2`, `Q3`, or `Q4`.
 */
export enum TimePeriodCompactPeriod {
    Fy = "FY",
    H1 = "H1",
    H2 = "H2",
    Q1 = "Q1",
    Q2 = "Q2",
    Q3 = "Q3",
    Q4 = "Q4",
}

/**
 * A generic Asana Resource, containing a globally unique identifier.
 */
export class TimePeriodCompact extends SpeakeasyBase {
    /**
     * A string representing the cadence code and the fiscal year.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "display_name" })
    displayName?: string;

    /**
     * The localized end date of the time period in `YYYY-MM-DD` format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "end_on" })
    endOn?: string;

    /**
     * Globally unique identifier of the resource, as a string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gid" })
    gid?: string;

    /**
     * The cadence and index of the time period. The value is one of: `FY`, `H1`, `H2`, `Q1`, `Q2`, `Q3`, or `Q4`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "period" })
    period?: TimePeriodCompactPeriod;

    /**
     * The base type of this resource.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_type" })
    resourceType?: string;

    /**
     * The localized start date of the time period in `YYYY-MM-DD` format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "start_on" })
    startOn?: string;
}
