/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * Information about the custom field setting.
 */
export class AddCustomFieldSettingForPortfolioRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.AddCustomFieldSettingRequest)
    data?: shared.AddCustomFieldSettingRequest;
}

export class AddCustomFieldSettingForPortfolioRequest extends SpeakeasyBase {
    /**
     * Information about the custom field setting.
     */
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody: AddCustomFieldSettingForPortfolioRequestBody;

    /**
     * Provides “pretty” output.
     *
     * @remarks
     * Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=opt_pretty" })
    optPretty?: boolean;

    /**
     * Globally unique identifier for the portfolio.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=portfolio_gid" })
    portfolioGid: string;
}

/**
 * Successfully added the custom field to the portfolio.
 */
export class AddCustomFieldSettingForPortfolio200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.CustomFieldSettingResponse)
    data?: shared.CustomFieldSettingResponse;
}

export class AddCustomFieldSettingForPortfolioResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * This usually occurs because of a missing or malformed parameter. Check the documentation and the syntax of your request and try again.
     */
    @SpeakeasyMetadata()
    errorResponse?: shared.ErrorResponse;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Successfully added the custom field to the portfolio.
     */
    @SpeakeasyMetadata()
    addCustomFieldSettingForPortfolio200ApplicationJSONObject?: AddCustomFieldSettingForPortfolio200ApplicationJSON;
}
