/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * The section to create.
 */
export class CreateSectionForProjectRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.SectionRequest)
    data?: shared.SectionRequest;
}

export class CreateSectionForProjectRequest extends SpeakeasyBase {
    /**
     * The section to create.
     */
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody: CreateSectionForProjectRequestBody;

    /**
     * Defines fields to return.
     *
     * @remarks
     * Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below.
     * The id of included objects will always be returned, regardless of the field options.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=false;name=opt_fields" })
    optFields?: string[];

    /**
     * Provides “pretty” output.
     *
     * @remarks
     * Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=opt_pretty" })
    optPretty?: boolean;

    /**
     * Globally unique identifier for the project.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=project_gid" })
    projectGid: string;
}

/**
 * Successfully created the specified section.
 */
export class CreateSectionForProject201ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.SectionResponse)
    data?: shared.SectionResponse;
}

export class CreateSectionForProjectResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * This usually occurs because of a missing or malformed parameter. Check the documentation and the syntax of your request and try again.
     */
    @SpeakeasyMetadata()
    errorResponse?: shared.ErrorResponse;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Successfully created the specified section.
     */
    @SpeakeasyMetadata()
    createSectionForProject201ApplicationJSONObject?: CreateSectionForProject201ApplicationJSON;
}
